#!/usr/bin/bash

#============================================================
# NODEPULSE - Decentralized node registry
# Intercepts the Cloudflare tunnel URL, signs an announcement
# with the node's RSA identity, and registers with the network
# via Original Seed nodes.
# Adapted for MSYS64 on Windows.
#
# Requires: ~/.nodepulse/private.pem, public.pem, node_id
# (generated by msys2-setup.sh)
#============================================================

NP_DIR="$HOME/nodepulse-bin"
PHP_BIN="$NP_DIR/php/php.exe"
CFLARED_BIN="$NP_DIR/cloudflared.exe"

PULSE_DIR="$HOME/www/nodepulse"
PULSE_LOG="$HOME/tmp/nodepulse.log"
NP_IDENTITY="$HOME/.nodepulse"
MAINT_PID_FILE="$HOME/tmp/.np_maint_pid"
NP_LOOP_PID_FILE="$HOME/tmp/.np_loop_pid"

mkdir -p "$PULSE_DIR" "$HOME/tmp"

# ---- Original Seed nodes (hardcoded) ----
SEEDS=(
    "https://www.plexum.net/nodepulse"
    "https://www.paraplant.com/nodepulse"
    "https://www.precisiongarage.it/nodepulse"
    "https://www.vertechsystem.com/nodepulse"
    "https://www.cdtel.it/nodepulse"
)

# ---- Load identity ----
if [ ! -f "$NP_IDENTITY/private.pem" ] || [ ! -f "$NP_IDENTITY/public.pem" ] || [ ! -f "$NP_IDENTITY/node_id" ]; then
    echo "[NodePulse] ERROR: Identity not found in $NP_IDENTITY"
    echo "[NodePulse] Run msys2-setup.sh first to generate identity."
    exit 1
fi

NODE_ID=$(cat "$NP_IDENTITY/node_id")
echo "[NodePulse] Identity loaded: node_id=$NODE_ID"

# ---- Initialize local DB ----
if [ ! -f "$PULSE_DIR/nodes.json" ]; then
    echo '{"last_id":0,"nodes":[]}' > "$PULSE_DIR/nodes.json"
fi

# PHP.exe needs Windows paths
PULSE_DB_WIN=$(cygpath -m "$PULSE_DIR/nodes.json")
PUBKEY_FILE_WIN=$(cygpath -m "$NP_IDENTITY/public.pem")

# ---- Select N random items from an array ----
select_random() {
    local count=$1
    shift
    local items=("$@")
    local total=${#items[@]}

    if [ "$total" -eq 0 ]; then
        return
    fi

    # If we want more than available, use all
    if [ "$count" -ge "$total" ]; then
        echo "${items[@]}"
        return
    fi

    # Shuffle using RANDOM
    local indices=()
    while [ ${#indices[@]} -lt "$count" ]; do
        local idx=$((RANDOM % total))
        local already=0
        for i in "${indices[@]}"; do
            if [ "$i" -eq "$idx" ]; then
                already=1
                break
            fi
        done
        if [ "$already" -eq 0 ]; then
            indices+=("$idx")
        fi
    done

    local selected=()
    for i in "${indices[@]}"; do
        selected+=("${items[$i]}")
    done
    echo "${selected[@]}"
}

# ---- Load announce targets: local peers + seeds ----
# Reads peers_online.json, extracts peer URLs, combines with seeds,
# deduplicates, and selects N random targets.
load_announce_targets() {
    local count=$1
    local PEERS_FILE="$PULSE_DIR/peers_online.json"
    local PEERS_FILE_WIN=$(cygpath -m "$PEERS_FILE")
    local ALL_TARGETS=()

    # Load peer URLs from local peers_online.json (if exists)
    if [ -f "$PEERS_FILE" ]; then
        local PEER_URLS
        PEER_URLS=$("$PHP_BIN" -d opcache.enable=0 -r "
            \$data = json_decode(file_get_contents('$PEERS_FILE_WIN'), true);
            if (\$data && isset(\$data['peers']) && is_array(\$data['peers'])) {
                // Sort by last_seen descending (most recent first)
                usort(\$data['peers'], function(\$a, \$b) {
                    return strcmp(
                        isset(\$b['last_seen']) ? \$b['last_seen'] : '',
                        isset(\$a['last_seen']) ? \$a['last_seen'] : ''
                    );
                });
                foreach (\$data['peers'] as \$p) {
                    if (isset(\$p['url']) && !empty(\$p['url'])) {
                        echo \$p['url'] . '/api.php' . \"\n\";
                    }
                }
            }
        " 2>/dev/null)

        if [ -n "$PEER_URLS" ]; then
            while IFS= read -r purl; do
                [ -n "$purl" ] && ALL_TARGETS+=("$purl")
            done <<< "$PEER_URLS"
            echo "[NodePulse] Loaded ${#ALL_TARGETS[@]} peers from local peers_online.json" >&2
        fi
    fi

    # Append seeds (with /api.php suffix for uniform format)
    for SEED in "${SEEDS[@]}"; do
        ALL_TARGETS+=("${SEED}/api.php")
    done

    # Deduplicate
    local UNIQUE_TARGETS=()
    for t in "${ALL_TARGETS[@]}"; do
        local dup=0
        for u in "${UNIQUE_TARGETS[@]}"; do
            if [ "$t" = "$u" ]; then
                dup=1
                break
            fi
        done
        [ "$dup" -eq 0 ] && UNIQUE_TARGETS+=("$t")
    done

    # Select N random
    select_random "$count" "${UNIQUE_TARGETS[@]}"
}

# ---- Sign and announce to seed nodes ----
announce_to_network() {
    local URL="$1"
    local TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    # Build payload and sign it
    local PAYLOAD="${NODE_ID}|${URL}|${TIMESTAMP}"
    local SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -sign "$NP_IDENTITY/private.pem" | base64 -w0)

    if [ -z "$SIGNATURE" ]; then
        echo "[NodePulse] ERROR: Failed to sign announcement"
        return 1
    fi

    # Create JSON body via PHP (handles PEM newline escaping perfectly)
    local TMPJSON="$HOME/tmp/.np_announce.json"
    local TMPJSON_WIN=$(cygpath -m "$TMPJSON")

    "$PHP_BIN" -d opcache.enable=0 -r "
        file_put_contents('$TMPJSON_WIN', json_encode(array(
            'node_id'    => '$NODE_ID',
            'public_key' => file_get_contents('$PUBKEY_FILE_WIN'),
            'url'        => '$URL',
            'type'       => 'tunnel',
            'signature'  => '$SIGNATURE',
            'signed_at'  => '$TIMESTAMP'
        )));
    "

    if [ ! -f "$TMPJSON" ]; then
        echo "[NodePulse] ERROR: Failed to create announcement JSON"
        return 1
    fi

    # Select targets: peers from local peers_online.json + seeds
    local CHOSEN_TARGETS
    read -ra CHOSEN_TARGETS <<< "$(load_announce_targets 8)"

    local SUCCESS=0
    local TOTAL=${#CHOSEN_TARGETS[@]}

    echo "[NodePulse] Announcing to $TOTAL targets (peers + seeds)..."

    for TARGET in "${CHOSEN_TARGETS[@]}"; do
        local RESPONSE=$(curl -s -m 10 -X POST "${TARGET}?action=announce" \
            -H "Content-Type: application/json" \
            -d @"$TMPJSON" \
            2>/dev/null)

        if echo "$RESPONSE" | grep -q '"ok":true'; then
            echo "[NodePulse]   -> $TARGET [OK]"
            SUCCESS=$((SUCCESS + 1))
        else
            local MSG=$(echo "$RESPONSE" | grep -oP '"message":"\K[^"]+' 2>/dev/null || echo "no response")
            echo "[NodePulse]   -> $TARGET [FAIL: $MSG]"
        fi
    done

    rm -f "$TMPJSON"

    echo "[NodePulse] Announced to $SUCCESS/$TOTAL seeds"

    if [ "$SUCCESS" -ge 1 ]; then
        return 0
    else
        echo "[NodePulse] WARNING: No seed accepted the announcement"
        return 1
    fi
}

# ---- Kill maintenance daemon if running ----
kill_maintenance_daemon() {
    if [ -f "$MAINT_PID_FILE" ]; then
        local MPID=$(cat "$MAINT_PID_FILE")
        if [ -n "$MPID" ] && kill -0 "$MPID" 2>/dev/null; then
            kill "$MPID" 2>/dev/null
            wait "$MPID" 2>/dev/null
            echo "[NodePulse] Maintenance daemon stopped (PID $MPID)"
        fi
        rm -f "$MAINT_PID_FILE"
    fi
}

# ---- Register node locally ----
register_node_local() {
    local URL="$1"
    local TIMESTAMP="$2"
    local CONNECTOR_ID="$3"
    local LOCATION="$4"
    local IP="$5"
    local PROTOCOL="$6"

    # Read last ID
    LAST_ID=$("$PHP_BIN" -d opcache.enable=0 -r "
        \$db = json_decode(file_get_contents('$PULSE_DB_WIN'), true);
        echo \$db['last_id'];
    ")
    NEW_ID=$((LAST_ID + 1))

    # Register the node via PHP
    "$PHP_BIN" -d opcache.enable=0 -r "
        \$db = json_decode(file_get_contents('$PULSE_DB_WIN'), true);
        \$db['last_id'] = $NEW_ID;
        \$db['nodes'][] = [
            'id' => $NEW_ID,
            'url' => '$URL',
            'connected_at' => '$TIMESTAMP',
            'connector_id' => '$CONNECTOR_ID',
            'location' => '$LOCATION',
            'ip' => '$IP',
            'protocol' => '$PROTOCOL',
            'status' => 'active'
        ];
        file_put_contents('$PULSE_DB_WIN', json_encode(\$db, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    "

    echo ""
    echo "============================================"
    echo "  NODEPULSE - Node #$NEW_ID registered!"
    echo "  node_id:  $NODE_ID"
    echo "  URL:      $URL"
    echo "  Location: $LOCATION"
    echo "  Protocol: $PROTOCOL"
    echo "============================================"
    echo ""
}

# ---- Main: cloudflared with built-in restart loop ----
# When cloudflared crashes, only cloudflared is restarted (nginx/php-cgi stay up).
# Backoff: 30s, 60s, 120s, 180s, 300s. Resets after 5 min of stable tunnel.
MAX_RETRIES=5
RETRY_DELAYS=(30 60 120 180 300)
CRASH_COUNT=0
STABLE_THRESHOLD=300  # tunnel up >5min = reset crash counter

# Save PID so stop-server can terminate this process
echo $$ > "$NP_LOOP_PID_FILE"
trap 'kill_maintenance_daemon; rm -f "$NP_LOOP_PID_FILE" "$HOME/tmp/.np_announce.json"; echo ""; echo "[NodePulse] Stopped."' INT TERM EXIT

while true; do
    echo ""
    echo "[NodePulse] Starting cloudflared tunnel..."
    echo ""

    TUNNEL_URL=""
    CONNECTOR_ID=""
    LOCATION=""
    NODE_IP=""
    PROTOCOL=""
    TIMESTAMP=""
    TUNNEL_START=$(date +%s)

    # Pipe cloudflared output and intercept the relevant fields
    "$CFLARED_BIN" tunnel --url http://127.0.0.1:8080 2>&1 | while IFS= read -r line; do
        echo "$line"

        # Capture tunnel URL
        if echo "$line" | grep -q "trycloudflare.com"; then
            TUNNEL_URL=$(echo "$line" | grep -oP 'https://[a-z0-9-]+\.trycloudflare\.com')
        fi

        # Capture Connector ID
        if echo "$line" | grep -q "Generated Connector ID"; then
            CONNECTOR_ID=$(echo "$line" | grep -oP 'ID: \K[a-f0-9-]+')
        fi

        # Capture timestamp, location, ip, protocol from the tunnel registration line
        if echo "$line" | grep -q "Registered tunnel connection"; then
            TIMESTAMP=$(echo "$line" | grep -oP '^\S+')
            LOCATION=$(echo "$line" | grep -oP 'location=\K[a-z0-9]+')
            NODE_IP=$(echo "$line" | grep -oP 'ip=\K[0-9.]+')
            PROTOCOL=$(echo "$line" | grep -oP 'protocol=\K\w+')

            if [ -n "$TUNNEL_URL" ]; then
                # Register locally (legacy)
                register_node_local "$TUNNEL_URL" "$TIMESTAMP" "$CONNECTOR_ID" "$LOCATION" "$NODE_IP" "$PROTOCOL"

                # Announce to the decentralized network (full nodepulse path for uniform URL format)
                announce_to_network "$TUNNEL_URL/nodepulse"

                # Start background maintenance daemon (kill previous if any)
                kill_maintenance_daemon
                "$PHP_BIN" -d opcache.enable=0 "$(cygpath -m "$PULSE_DIR/np_maintenance_daemon.php")" "$TUNNEL_URL/nodepulse" &
                echo $! > "$MAINT_PID_FILE"
                echo "[NodePulse] Maintenance daemon active (PID $!)"
            fi
        fi
    done

    # Cloudflared exited — was it a manual stop or a crash?
    # If stop-server killed us, the PID file is gone (trap removed it)
    if [ ! -f "$NP_LOOP_PID_FILE" ]; then
        break
    fi

    # Kill maintenance daemon (tunnel is dead, no point keeping it)
    kill_maintenance_daemon

    # If tunnel was stable (>5min), reset crash counter
    TUNNEL_DURATION=$(( $(date +%s) - TUNNEL_START ))
    if [ "$TUNNEL_DURATION" -ge "$STABLE_THRESHOLD" ]; then
        CRASH_COUNT=0
    fi

    CRASH_COUNT=$((CRASH_COUNT + 1))
    echo ""
    echo "[NodePulse] Tunnel crashed after ${TUNNEL_DURATION}s (attempt $CRASH_COUNT/$MAX_RETRIES)"

    if [ "$CRASH_COUNT" -ge "$MAX_RETRIES" ]; then
        echo "[NodePulse] Too many crashes. Giving up."
        echo "[NodePulse] Run 'start-server' to try again."
        break
    fi

    DELAY=${RETRY_DELAYS[$((CRASH_COUNT - 1))]}
    echo "[NodePulse] Restarting cloudflared in ${DELAY}s..."
    sleep "$DELAY"
done
